
#ifndef DIAE_ERRORS_H
#define DIAE_ERRORS_H

#define DIAE_OK 0

#define DIAE_PARAM_IS_NULL -1
#define DIAE_COMMAND_NOT_TERMINATED -2
#define DIAE_COMMAND_WRONG_FORMAT -3
#define DIAE_COMMAND_EMPTY -4
#define DIAE_COMMAND_UNEXPECTED_END -5
#define DIAE_COMMAND_WRONG_TYPE -6

#define NO_DEVICE -100

#endif
